// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/solo-io/gloo-portal-idp-connect/internal/okta/server (interfaces: OktaClient,ApplicationAPI,ApiCreateApplicationRequest,ApiListApplicationsRequest,ApiDeactivateApplicationRequest,ApiDeleteApplicationRequest)
//
// Generated by this command:
//
//	mockgen -destination=mock/okta_client.go . OktaClient,ApplicationAPI,ApiCreateApplicationRequest,ApiListApplicationsRequest,ApiDeactivateApplicationRequest,ApiDeleteApplicationRequest
//

// Package mock_server is a generated GoMock package.
package mock_server

import (
	context "context"
	reflect "reflect"

	okta "github.com/okta/okta-sdk-golang/v5/okta"
	server "github.com/solo-io/gloo-portal-idp-connect/internal/okta/server"
	gomock "go.uber.org/mock/gomock"
)

// MockOktaClient is a mock of OktaClient interface.
type MockOktaClient struct {
	ctrl     *gomock.Controller
	recorder *MockOktaClientMockRecorder
	isgomock struct{}
}

// MockOktaClientMockRecorder is the mock recorder for MockOktaClient.
type MockOktaClientMockRecorder struct {
	mock *MockOktaClient
}

// NewMockOktaClient creates a new mock instance.
func NewMockOktaClient(ctrl *gomock.Controller) *MockOktaClient {
	mock := &MockOktaClient{ctrl: ctrl}
	mock.recorder = &MockOktaClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOktaClient) EXPECT() *MockOktaClientMockRecorder {
	return m.recorder
}

// GetApplicationAPI mocks base method.
func (m *MockOktaClient) GetApplicationAPI() server.ApplicationAPI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApplicationAPI")
	ret0, _ := ret[0].(server.ApplicationAPI)
	return ret0
}

// GetApplicationAPI indicates an expected call of GetApplicationAPI.
func (mr *MockOktaClientMockRecorder) GetApplicationAPI() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApplicationAPI", reflect.TypeOf((*MockOktaClient)(nil).GetApplicationAPI))
}

// MockApplicationAPI is a mock of ApplicationAPI interface.
type MockApplicationAPI struct {
	ctrl     *gomock.Controller
	recorder *MockApplicationAPIMockRecorder
	isgomock struct{}
}

// MockApplicationAPIMockRecorder is the mock recorder for MockApplicationAPI.
type MockApplicationAPIMockRecorder struct {
	mock *MockApplicationAPI
}

// NewMockApplicationAPI creates a new mock instance.
func NewMockApplicationAPI(ctrl *gomock.Controller) *MockApplicationAPI {
	mock := &MockApplicationAPI{ctrl: ctrl}
	mock.recorder = &MockApplicationAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApplicationAPI) EXPECT() *MockApplicationAPIMockRecorder {
	return m.recorder
}

// CreateApplication mocks base method.
func (m *MockApplicationAPI) CreateApplication(ctx context.Context) server.ApiCreateApplicationRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateApplication", ctx)
	ret0, _ := ret[0].(server.ApiCreateApplicationRequest)
	return ret0
}

// CreateApplication indicates an expected call of CreateApplication.
func (mr *MockApplicationAPIMockRecorder) CreateApplication(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateApplication", reflect.TypeOf((*MockApplicationAPI)(nil).CreateApplication), ctx)
}

// DeactivateApplication mocks base method.
func (m *MockApplicationAPI) DeactivateApplication(ctx context.Context, appId string) server.ApiDeactivateApplicationRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateApplication", ctx, appId)
	ret0, _ := ret[0].(server.ApiDeactivateApplicationRequest)
	return ret0
}

// DeactivateApplication indicates an expected call of DeactivateApplication.
func (mr *MockApplicationAPIMockRecorder) DeactivateApplication(ctx, appId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateApplication", reflect.TypeOf((*MockApplicationAPI)(nil).DeactivateApplication), ctx, appId)
}

// DeleteApplication mocks base method.
func (m *MockApplicationAPI) DeleteApplication(ctx context.Context, appId string) server.ApiDeleteApplicationRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteApplication", ctx, appId)
	ret0, _ := ret[0].(server.ApiDeleteApplicationRequest)
	return ret0
}

// DeleteApplication indicates an expected call of DeleteApplication.
func (mr *MockApplicationAPIMockRecorder) DeleteApplication(ctx, appId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteApplication", reflect.TypeOf((*MockApplicationAPI)(nil).DeleteApplication), ctx, appId)
}

// ListApplications mocks base method.
func (m *MockApplicationAPI) ListApplications(ctx context.Context) server.ApiListApplicationsRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListApplications", ctx)
	ret0, _ := ret[0].(server.ApiListApplicationsRequest)
	return ret0
}

// ListApplications indicates an expected call of ListApplications.
func (mr *MockApplicationAPIMockRecorder) ListApplications(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListApplications", reflect.TypeOf((*MockApplicationAPI)(nil).ListApplications), ctx)
}

// MockApiCreateApplicationRequest is a mock of ApiCreateApplicationRequest interface.
type MockApiCreateApplicationRequest struct {
	ctrl     *gomock.Controller
	recorder *MockApiCreateApplicationRequestMockRecorder
	isgomock struct{}
}

// MockApiCreateApplicationRequestMockRecorder is the mock recorder for MockApiCreateApplicationRequest.
type MockApiCreateApplicationRequestMockRecorder struct {
	mock *MockApiCreateApplicationRequest
}

// NewMockApiCreateApplicationRequest creates a new mock instance.
func NewMockApiCreateApplicationRequest(ctrl *gomock.Controller) *MockApiCreateApplicationRequest {
	mock := &MockApiCreateApplicationRequest{ctrl: ctrl}
	mock.recorder = &MockApiCreateApplicationRequestMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApiCreateApplicationRequest) EXPECT() *MockApiCreateApplicationRequestMockRecorder {
	return m.recorder
}

// Application mocks base method.
func (m *MockApiCreateApplicationRequest) Application(application okta.ListApplications200ResponseInner) server.ApiCreateApplicationRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Application", application)
	ret0, _ := ret[0].(server.ApiCreateApplicationRequest)
	return ret0
}

// Application indicates an expected call of Application.
func (mr *MockApiCreateApplicationRequestMockRecorder) Application(application any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Application", reflect.TypeOf((*MockApiCreateApplicationRequest)(nil).Application), application)
}

// Execute mocks base method.
func (m *MockApiCreateApplicationRequest) Execute() (*okta.ListApplications200ResponseInner, *okta.APIResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute")
	ret0, _ := ret[0].(*okta.ListApplications200ResponseInner)
	ret1, _ := ret[1].(*okta.APIResponse)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Execute indicates an expected call of Execute.
func (mr *MockApiCreateApplicationRequestMockRecorder) Execute() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockApiCreateApplicationRequest)(nil).Execute))
}

// MockApiListApplicationsRequest is a mock of ApiListApplicationsRequest interface.
type MockApiListApplicationsRequest struct {
	ctrl     *gomock.Controller
	recorder *MockApiListApplicationsRequestMockRecorder
	isgomock struct{}
}

// MockApiListApplicationsRequestMockRecorder is the mock recorder for MockApiListApplicationsRequest.
type MockApiListApplicationsRequestMockRecorder struct {
	mock *MockApiListApplicationsRequest
}

// NewMockApiListApplicationsRequest creates a new mock instance.
func NewMockApiListApplicationsRequest(ctrl *gomock.Controller) *MockApiListApplicationsRequest {
	mock := &MockApiListApplicationsRequest{ctrl: ctrl}
	mock.recorder = &MockApiListApplicationsRequestMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApiListApplicationsRequest) EXPECT() *MockApiListApplicationsRequestMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockApiListApplicationsRequest) Execute() ([]okta.ListApplications200ResponseInner, *okta.APIResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute")
	ret0, _ := ret[0].([]okta.ListApplications200ResponseInner)
	ret1, _ := ret[1].(*okta.APIResponse)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Execute indicates an expected call of Execute.
func (mr *MockApiListApplicationsRequestMockRecorder) Execute() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockApiListApplicationsRequest)(nil).Execute))
}

// MockApiDeactivateApplicationRequest is a mock of ApiDeactivateApplicationRequest interface.
type MockApiDeactivateApplicationRequest struct {
	ctrl     *gomock.Controller
	recorder *MockApiDeactivateApplicationRequestMockRecorder
	isgomock struct{}
}

// MockApiDeactivateApplicationRequestMockRecorder is the mock recorder for MockApiDeactivateApplicationRequest.
type MockApiDeactivateApplicationRequestMockRecorder struct {
	mock *MockApiDeactivateApplicationRequest
}

// NewMockApiDeactivateApplicationRequest creates a new mock instance.
func NewMockApiDeactivateApplicationRequest(ctrl *gomock.Controller) *MockApiDeactivateApplicationRequest {
	mock := &MockApiDeactivateApplicationRequest{ctrl: ctrl}
	mock.recorder = &MockApiDeactivateApplicationRequestMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApiDeactivateApplicationRequest) EXPECT() *MockApiDeactivateApplicationRequestMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockApiDeactivateApplicationRequest) Execute() (*okta.APIResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute")
	ret0, _ := ret[0].(*okta.APIResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockApiDeactivateApplicationRequestMockRecorder) Execute() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockApiDeactivateApplicationRequest)(nil).Execute))
}

// MockApiDeleteApplicationRequest is a mock of ApiDeleteApplicationRequest interface.
type MockApiDeleteApplicationRequest struct {
	ctrl     *gomock.Controller
	recorder *MockApiDeleteApplicationRequestMockRecorder
	isgomock struct{}
}

// MockApiDeleteApplicationRequestMockRecorder is the mock recorder for MockApiDeleteApplicationRequest.
type MockApiDeleteApplicationRequestMockRecorder struct {
	mock *MockApiDeleteApplicationRequest
}

// NewMockApiDeleteApplicationRequest creates a new mock instance.
func NewMockApiDeleteApplicationRequest(ctrl *gomock.Controller) *MockApiDeleteApplicationRequest {
	mock := &MockApiDeleteApplicationRequest{ctrl: ctrl}
	mock.recorder = &MockApiDeleteApplicationRequestMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApiDeleteApplicationRequest) EXPECT() *MockApiDeleteApplicationRequestMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockApiDeleteApplicationRequest) Execute() (*okta.APIResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute")
	ret0, _ := ret[0].(*okta.APIResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockApiDeleteApplicationRequestMockRecorder) Execute() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockApiDeleteApplicationRequest)(nil).Execute))
}
