version: "2"

run:
  timeout: 5m
  tests: false # Don't run linters on test files to avoid issues with Ginkgo dot imports

linters:
  default: standard
  settings:
    staticcheck:
      # https://staticcheck.dev/docs/configuration/options/#dot_import_whitelist
      # Default: ["github.com/mmcloughlin/avo/build", "github.com/mmcloughlin/avo/operand", "github.com/mmcloughlin/avo/reg"]
      dot-import-whitelist:
      - github.com/onsi/ginkgo/v2
      - github.com/onsi/gomega
