{{- if eq .Values.connector "cognito"}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.cognito.aws.secretName }}
  namespace: {{ .Release.Namespace }}
data:
  secretAccessKey: {{ .Values.cognito.aws.secretAccessKey | b64enc }}
  {{- if .Values.cognito.aws.sessionToken }}
  sessionToken: {{ .Values.cognito.aws.sessionToken | b64enc }}
  {{- end}}
{{- end}}