version: 2.1

orbs:
  helm: circleci/helm@1.1.2
  slack: circleci/slack@4.9.3

jobs:
  kind-tests:
    parameters:
      test_type:
        type: string
    parallelism: 1
    machine:
      image: ubuntu-2004:2022.07.1
      resource_class: large
    working_directory: ~/go/src/github.com/solo-io/gloo-portal-idp-connect
    steps:
      - checkout
      - install_dependencies
      - run:
          name: << parameters.test_type >>
          command: |
            make run-<< parameters.test_type >>-tests

workflows:
  build:
    # Run when branch != main
    when:
      and:
        - not:
            equal: ["main", << pipeline.git.branch >>]
    jobs:
      - kind-tests:
          matrix:
            parameters:
              test_type:
                - "e2e"
commands:
  install_dependencies:
    description: "A command to install dependencies for gloo mesh tests"
    parameters:
      go_version:
        type: string
        default: "1.21.5"
      helm_version:
        type: string
        default: "v3.12.3"
      kube_version:
        type: string
        default: "1.21.5"
      kind_version:
        type: string
        default: "v0.19.0"
    steps:
      - run:
          name: install dependencies
          command: |
            export GO_VERSION=<< parameters.go_version >> 
            export HELM_VERSION=<< parameters.helm_version >>
            export KUBECTL_VERSION=<< parameters.kube_version >>
            export KIND_VERSION=<< parameters.kind_version >>
            echo "Installing dependencies using GO_VERSION($GO_VERSION), HELM_VERSION($HELM_VERSION), KUBECTL_VERSION($KUBECTL_VERSION), KIND_VERSION($KIND_VERSION)"
            ./ci/circleci/install-dependencies.sh
            
            make install-tools
