// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package v1

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Creates API Product in the OpenID Connect Provider. Then, you can add this API Product to the application for your Portal applications with the `PUT /applications/{id}/api-products` API request.
	// (POST /api-products)
	CreateAPIProduct(ctx echo.Context) error
	// Deletes API Product in the OpenID Connect Provider.
	// (DELETE /api-products/{name})
	DeleteAPIProduct(ctx echo.Context, name string) error
	// Creates an application of type oauth2.
	// (POST /applications/oauth2)
	CreateOAuthApplication(ctx echo.Context) error
	// Deletes an application in the OpenID Connect Provider.
	// (DELETE /applications/{id})
	DeleteApplication(ctx echo.Context, id string) error
	// Updates the set of API Products that the application has access to in the OpenID Connect Provider.
	// (PUT /applications/{id}/api-products)
	UpdateAppAPIProducts(ctx echo.Context, id string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// CreateAPIProduct converts echo context to params.
func (w *ServerInterfaceWrapper) CreateAPIProduct(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateAPIProduct(ctx)
	return err
}

// DeleteAPIProduct converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteAPIProduct(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", ctx.Param("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteAPIProduct(ctx, name)
	return err
}

// CreateOAuthApplication converts echo context to params.
func (w *ServerInterfaceWrapper) CreateOAuthApplication(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateOAuthApplication(ctx)
	return err
}

// DeleteApplication converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteApplication(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteApplication(ctx, id)
	return err
}

// UpdateAppAPIProducts converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateAppAPIProducts(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateAppAPIProducts(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/api-products", wrapper.CreateAPIProduct)
	router.DELETE(baseURL+"/api-products/:name", wrapper.DeleteAPIProduct)
	router.POST(baseURL+"/applications/oauth2", wrapper.CreateOAuthApplication)
	router.DELETE(baseURL+"/applications/:id", wrapper.DeleteApplication)
	router.PUT(baseURL+"/applications/:id/api-products", wrapper.UpdateAppAPIProducts)

}

type CreateAPIProductRequestObject struct {
	Body *CreateAPIProductJSONRequestBody
}

type CreateAPIProductResponseObject interface {
	VisitCreateAPIProductResponse(w http.ResponseWriter) error
}

type CreateAPIProduct201Response struct {
}

func (response CreateAPIProduct201Response) VisitCreateAPIProductResponse(w http.ResponseWriter) error {
	w.WriteHeader(201)
	return nil
}

type CreateAPIProduct400JSONResponse Error

func (response CreateAPIProduct400JSONResponse) VisitCreateAPIProductResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateAPIProduct409JSONResponse Error

func (response CreateAPIProduct409JSONResponse) VisitCreateAPIProductResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type CreateAPIProduct500JSONResponse Error

func (response CreateAPIProduct500JSONResponse) VisitCreateAPIProductResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteAPIProductRequestObject struct {
	Name string `json:"name"`
}

type DeleteAPIProductResponseObject interface {
	VisitDeleteAPIProductResponse(w http.ResponseWriter) error
}

type DeleteAPIProduct204Response struct {
}

func (response DeleteAPIProduct204Response) VisitDeleteAPIProductResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteAPIProduct404JSONResponse Error

func (response DeleteAPIProduct404JSONResponse) VisitDeleteAPIProductResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteAPIProduct500JSONResponse Error

func (response DeleteAPIProduct500JSONResponse) VisitDeleteAPIProductResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateOAuthApplicationRequestObject struct {
	Body *CreateOAuthApplicationJSONRequestBody
}

type CreateOAuthApplicationResponseObject interface {
	VisitCreateOAuthApplicationResponse(w http.ResponseWriter) error
}

type CreateOAuthApplication201JSONResponse struct {
	ClientId     *string `json:"clientId,omitempty"`
	ClientName   *string `json:"clientName,omitempty"`
	ClientSecret *string `json:"clientSecret,omitempty"`
}

func (response CreateOAuthApplication201JSONResponse) VisitCreateOAuthApplicationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateOAuthApplication400JSONResponse Error

func (response CreateOAuthApplication400JSONResponse) VisitCreateOAuthApplicationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateOAuthApplication500JSONResponse Error

func (response CreateOAuthApplication500JSONResponse) VisitCreateOAuthApplicationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteApplicationRequestObject struct {
	Id string `json:"id"`
}

type DeleteApplicationResponseObject interface {
	VisitDeleteApplicationResponse(w http.ResponseWriter) error
}

type DeleteApplication204Response struct {
}

func (response DeleteApplication204Response) VisitDeleteApplicationResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteApplication404JSONResponse Error

func (response DeleteApplication404JSONResponse) VisitDeleteApplicationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteApplication500JSONResponse Error

func (response DeleteApplication500JSONResponse) VisitDeleteApplicationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateAppAPIProductsRequestObject struct {
	Id   string `json:"id"`
	Body *UpdateAppAPIProductsJSONRequestBody
}

type UpdateAppAPIProductsResponseObject interface {
	VisitUpdateAppAPIProductsResponse(w http.ResponseWriter) error
}

type UpdateAppAPIProducts204Response struct {
}

func (response UpdateAppAPIProducts204Response) VisitUpdateAppAPIProductsResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type UpdateAppAPIProducts400JSONResponse Error

func (response UpdateAppAPIProducts400JSONResponse) VisitUpdateAppAPIProductsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateAppAPIProducts404JSONResponse Error

func (response UpdateAppAPIProducts404JSONResponse) VisitUpdateAppAPIProductsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateAppAPIProducts500JSONResponse Error

func (response UpdateAppAPIProducts500JSONResponse) VisitUpdateAppAPIProductsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Creates API Product in the OpenID Connect Provider. Then, you can add this API Product to the application for your Portal applications with the `PUT /applications/{id}/api-products` API request.
	// (POST /api-products)
	CreateAPIProduct(ctx context.Context, request CreateAPIProductRequestObject) (CreateAPIProductResponseObject, error)
	// Deletes API Product in the OpenID Connect Provider.
	// (DELETE /api-products/{name})
	DeleteAPIProduct(ctx context.Context, request DeleteAPIProductRequestObject) (DeleteAPIProductResponseObject, error)
	// Creates an application of type oauth2.
	// (POST /applications/oauth2)
	CreateOAuthApplication(ctx context.Context, request CreateOAuthApplicationRequestObject) (CreateOAuthApplicationResponseObject, error)
	// Deletes an application in the OpenID Connect Provider.
	// (DELETE /applications/{id})
	DeleteApplication(ctx context.Context, request DeleteApplicationRequestObject) (DeleteApplicationResponseObject, error)
	// Updates the set of API Products that the application has access to in the OpenID Connect Provider.
	// (PUT /applications/{id}/api-products)
	UpdateAppAPIProducts(ctx context.Context, request UpdateAppAPIProductsRequestObject) (UpdateAppAPIProductsResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// CreateAPIProduct operation middleware
func (sh *strictHandler) CreateAPIProduct(ctx echo.Context) error {
	var request CreateAPIProductRequestObject

	var body CreateAPIProductJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateAPIProduct(ctx.Request().Context(), request.(CreateAPIProductRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateAPIProduct")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateAPIProductResponseObject); ok {
		return validResponse.VisitCreateAPIProductResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteAPIProduct operation middleware
func (sh *strictHandler) DeleteAPIProduct(ctx echo.Context, name string) error {
	var request DeleteAPIProductRequestObject

	request.Name = name

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteAPIProduct(ctx.Request().Context(), request.(DeleteAPIProductRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteAPIProduct")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteAPIProductResponseObject); ok {
		return validResponse.VisitDeleteAPIProductResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateOAuthApplication operation middleware
func (sh *strictHandler) CreateOAuthApplication(ctx echo.Context) error {
	var request CreateOAuthApplicationRequestObject

	var body CreateOAuthApplicationJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateOAuthApplication(ctx.Request().Context(), request.(CreateOAuthApplicationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateOAuthApplication")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateOAuthApplicationResponseObject); ok {
		return validResponse.VisitCreateOAuthApplicationResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteApplication operation middleware
func (sh *strictHandler) DeleteApplication(ctx echo.Context, id string) error {
	var request DeleteApplicationRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteApplication(ctx.Request().Context(), request.(DeleteApplicationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteApplication")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteApplicationResponseObject); ok {
		return validResponse.VisitDeleteApplicationResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateAppAPIProducts operation middleware
func (sh *strictHandler) UpdateAppAPIProducts(ctx echo.Context, id string) error {
	var request UpdateAppAPIProductsRequestObject

	request.Id = id

	var body UpdateAppAPIProductsJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateAppAPIProducts(ctx.Request().Context(), request.(UpdateAppAPIProductsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateAppAPIProducts")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateAppAPIProductsResponseObject); ok {
		return validResponse.VisitUpdateAppAPIProductsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
