// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZ328buRH+VwZsgSbAWlIcubH0prPbQigaC/EFfTgYEE3OSjxzyQ3JlaMa+t8L/tjV",
	"WruOFDR3OSB9srzkkMNv5vs4s/tEmC5KrVA5S6ZPxLI1FjT8/Jsx2vgfpdElGicwPGaao//rtiWSKRHK",
	"4QoN2WWkQGvpKgziZ1qU0o/fOuoqC1eaI/wrTchqY+uMUCtva5BarZ6bBgcgjXRsgtGnShjkZPpLdGvv",
	"Q7Pi3S4jt0yX2D0JR8uMKJ043Dj9AuvtoD2tx/MNlRX22p8F+6OexwWyZ+7c7fwsoXLdcZT8hLk2CFtd",
	"wT2uhMrAooOqhH9IrWEhqcu1KWChjaMSHoVb+7kGbkpU82u40kohc/DqZn599RpKozeCoxnAz2tUGcyv",
	"F82U2WKehX0YVVBQRVcIbo3ApPD5AlTxiJEFodIm8+urZk1wa+pghQ6otZoJ6pC3HEoe0rK0A/i7NlD4",
	"c/lDm4L6w/qTxR1/6T0b18zevVo7V9rpcOj/G1gt9UDo4UpqfVaGaUNJHVo3fD3woRAuhKh3vYOzk4xs",
	"0NiI+pvBaDDy8dYlKloKMiVvw6OMlNStQ0INEzAh1bR13dhdGfTOAE0Yetz8+XxsYM6b3RfPEPQz2r4J",
	"n10FKhdQgkBBE9b14A7gvXa4t1zGrW6RGXRLEBYUbtCAddogrz3g1NF7ajEEVViwa/2owOkwWFk0oJXc",
	"glYMB/BPxBLc2k8Lq/p5BX1AyCtXGQSf3midre1ni7lPCl4xZ+sNI+YDmHNUTrgtOP2Aym9dk8Nbb6gU",
	"nLaPE3wRtpNSfmwlNqgStD7anu0BozlvwL8KoyRyEK37SfNt1DXl/MD0idCylIIFw+GvSZaiMPbIYVju",
	"PS1e0ADv7lmptTzjuEHpTc/e9OlISa11a6Or1bolr/r+V2Suq3b7Xe+yztxddpB2rz4k29ewt4RcG2Ae",
	"E6FWoPwTnbf4PYBly6eQOFwYZE5uwQ/EAB3JzRC2RyFl3KmtH8dyf0DaZ3amwgCCLbWyEfvz0Zv/OXI+",
	"M9pxo6PLyTv8Kx8hnYzzi8sJe3t5/u7yntExTt6Oz/tC981yoM3U50uxyZjf84vLc34xGeMlpaPx5O04",
	"n7B3mI/yi/MjGfUhwfZs0Sfy0aJZaC0TJ6ZPZCalfkR+M6vcOlyb1qcbFlTIyCcluL+dsp4EPZqGtxVj",
	"aG1eSblN+cAbtu4ycjEafVU8/2wwJ1Pyp+G+hhmmAmYYq5ceJz4q/Fwi81tjKDAaCjSe7DJiq6KgZntE",
	"slvXaTtrHV0F2K7SdRDwqi+H4ZPgu3gzSHTYvSOuw/MXVSwONypWUkMLdGj8jk8v835+Hfkez+A0xO39",
	"+sJP9ZcYyYgKSUwE75AvawHfKWgON74JP6iPs1BMVhyhlY3hsgHqMfVBhbhO48qnCs1270tbGL/kxF1H",
	"HcZdcJ+lYITgWQqOo9Fvm4IxeKC0g1xXin/H5A8QvJz8Mdm+cfIPbRKWJ1JWPUXSxzLc+AmlqEJdHsRZ",
	"cVJSqtPZkNaeX3smUJ7KWHD62/Dh7ltVFwdFQY90Byw6Fw3pyrH3t4ZdOCzsV/UszQNqDN126pG09Cm1",
	"yKxB2+sRBVsiE7lgLcE7dusf4zXlHJvOxOkfmd+U8z27EySHJJ9xbhsCnEr1F5m+z7IvX3D1lsc6oJgl",
	"sbKvlPhUIYjQMuTCd63XIs/RBDLXjURt2uoR6mQInQJvTIKBQDuAuYLZv2/97iuRqto2ZvCoK8nhHpuy",
	"Jbq1/IBWV4bhLZoNmmX9uGbnMvPne8Atk5o+fM2yVBbR+ObB35WnmfmqTRvxn1h71z49rgVb97VMNC6+",
	"nO0TcQkbQYEqWM4CoWChpWDbZUSocutR5jkbI2ePofHizqH/912h363uEFthfaHquU3idKrMv281NQk5",
	"/AsHKR6wpwQ6qDtqJfxty6DvV/WE8/1+ohhi98eqeWoEekuejjodqXdSDXLnG68vvvs5Sfb+L2w/iLDF",
	"rLhtac0fsWo8Rr7of29VeFJRGFFo14V9uB6SJTUVJ78oOuFtRFsUJ7+XKFJpkPIt4Gdh/XG+/6uQXmV8",
	"UcD6lDF9Tqi/Hvgey63RYqssb4lGejtx+Flg/2Z3ufj4M6Qust1ELgPBEm361DgcIbA21gqVkWRK6m8G",
	"tBSD+KkgfQpI3wwGTBfDzRuyu9v9NwAA//+2rtD6IhsAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
