// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package v1

// ApiProduct defines model for ApiProduct.
type ApiProduct struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// Error defines model for Error.
type Error struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Reason  string `json:"reason"`
}

// CreateAPIProductJSONBody defines parameters for CreateAPIProduct.
type CreateAPIProductJSONBody struct {
	ApiProduct  ApiProduct              `json:"apiProduct"`
	Passthrough *map[string]interface{} `json:"passthrough,omitempty"`
}

// DeleteAPIProductParams defines parameters for DeleteAPIProduct.
type DeleteAPIProductParams struct {
	// Passthrough Optionally include passthrough data.
	Passthrough *string `form:"passthrough,omitempty" json:"passthrough,omitempty"`
}

// CreateClientJSONBody defines parameters for CreateClient.
type CreateClientJSONBody struct {
	ClientName  string                  `json:"clientName"`
	Passthrough *map[string]interface{} `json:"passthrough,omitempty"`
}

// DeleteClientParams defines parameters for DeleteClient.
type DeleteClientParams struct {
	// Passthrough Optionally include passthrough data as a json string.
	Passthrough *string `form:"passthrough,omitempty" json:"passthrough,omitempty"`
}

// UpdateClientAPIProductsJSONBody defines parameters for UpdateClientAPIProducts.
type UpdateClientAPIProductsJSONBody struct {
	ApiProducts []string                `json:"apiProducts"`
	Passthrough *map[string]interface{} `json:"passthrough,omitempty"`
}

// CreateAPIProductJSONRequestBody defines body for CreateAPIProduct for application/json ContentType.
type CreateAPIProductJSONRequestBody CreateAPIProductJSONBody

// CreateClientJSONRequestBody defines body for CreateClient for application/json ContentType.
type CreateClientJSONRequestBody CreateClientJSONBody

// UpdateClientAPIProductsJSONRequestBody defines body for UpdateClientAPIProducts for application/json ContentType.
type UpdateClientAPIProductsJSONRequestBody UpdateClientAPIProductsJSONBody
