// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package v1

const (
	IdentityTokenScopes = "identityToken.Scopes"
)

// Error defines model for Error.
type Error struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Reason  string `json:"reason"`
}

// Scope defines model for Scope.
type Scope struct {
	Description string `json:"description"`
	Value       string `json:"value"`
}

// DeleteClientParams defines parameters for DeleteClient.
type DeleteClientParams struct {
	// Id (Required) ID for client to delete.
	Id string `form:"id" json:"id"`

	// Passthrough Optionally include passthrough data as a json string
	Passthrough *string `form:"passthrough,omitempty" json:"passthrough,omitempty"`
}

// CreateClientJSONBody defines parameters for CreateClient.
type CreateClientJSONBody struct {
	ClientName  string                  `json:"clientName"`
	Passthrough *map[string]interface{} `json:"passthrough,omitempty"`
}

// UpdateClientScopesJSONBody defines parameters for UpdateClientScopes.
type UpdateClientScopesJSONBody struct {
	Passthrough *map[string]interface{} `json:"passthrough,omitempty"`
	Scopes      []string                `json:"scopes"`
}

// DeleteScopeParams defines parameters for DeleteScope.
type DeleteScopeParams struct {
	// Scope (Required) Name of the scope we'd like to delete.
	Scope string `form:"scope" json:"scope"`

	// Passthrough Optionally include passthrough data
	Passthrough *string `form:"passthrough,omitempty" json:"passthrough,omitempty"`
}

// CreateScopeJSONBody defines parameters for CreateScope.
type CreateScopeJSONBody struct {
	Passthrough *map[string]interface{} `json:"passthrough,omitempty"`
	Scope       Scope                   `json:"scope"`
}

// CreateClientJSONRequestBody defines body for CreateClient for application/json ContentType.
type CreateClientJSONRequestBody CreateClientJSONBody

// UpdateClientScopesJSONRequestBody defines body for UpdateClientScopes for application/json ContentType.
type UpdateClientScopesJSONRequestBody UpdateClientScopesJSONBody

// CreateScopeJSONRequestBody defines body for CreateScope for application/json ContentType.
type CreateScopeJSONRequestBody CreateScopeJSONBody
