// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/solo-io/gloo-portal-idp-connect/internal/cognito/server (interfaces: CognitoClient)
//
// Generated by this command:
//
//	mockgen -destination=mock/cognito_client.go . CognitoClient
//

// Package mock_server is a generated GoMock package.
package mock_server

import (
	context "context"
	reflect "reflect"

	cognitoidentityprovider "github.com/aws/aws-sdk-go-v2/service/cognitoidentityprovider"
	gomock "go.uber.org/mock/gomock"
)

// MockCognitoClient is a mock of CognitoClient interface.
type MockCognitoClient struct {
	ctrl     *gomock.Controller
	recorder *MockCognitoClientMockRecorder
	isgomock struct{}
}

// MockCognitoClientMockRecorder is the mock recorder for MockCognitoClient.
type MockCognitoClientMockRecorder struct {
	mock *MockCognitoClient
}

// NewMockCognitoClient creates a new mock instance.
func NewMockCognitoClient(ctrl *gomock.Controller) *MockCognitoClient {
	mock := &MockCognitoClient{ctrl: ctrl}
	mock.recorder = &MockCognitoClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCognitoClient) EXPECT() *MockCognitoClientMockRecorder {
	return m.recorder
}

// CreateResourceServer mocks base method.
func (m *MockCognitoClient) CreateResourceServer(ctx context.Context, params *cognitoidentityprovider.CreateResourceServerInput, optFns ...func(*cognitoidentityprovider.Options)) (*cognitoidentityprovider.CreateResourceServerOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateResourceServer", varargs...)
	ret0, _ := ret[0].(*cognitoidentityprovider.CreateResourceServerOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateResourceServer indicates an expected call of CreateResourceServer.
func (mr *MockCognitoClientMockRecorder) CreateResourceServer(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateResourceServer", reflect.TypeOf((*MockCognitoClient)(nil).CreateResourceServer), varargs...)
}

// CreateUserPoolClient mocks base method.
func (m *MockCognitoClient) CreateUserPoolClient(ctx context.Context, params *cognitoidentityprovider.CreateUserPoolClientInput, optFns ...func(*cognitoidentityprovider.Options)) (*cognitoidentityprovider.CreateUserPoolClientOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateUserPoolClient", varargs...)
	ret0, _ := ret[0].(*cognitoidentityprovider.CreateUserPoolClientOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserPoolClient indicates an expected call of CreateUserPoolClient.
func (mr *MockCognitoClientMockRecorder) CreateUserPoolClient(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserPoolClient", reflect.TypeOf((*MockCognitoClient)(nil).CreateUserPoolClient), varargs...)
}

// DeleteUserPoolClient mocks base method.
func (m *MockCognitoClient) DeleteUserPoolClient(ctx context.Context, params *cognitoidentityprovider.DeleteUserPoolClientInput, optFns ...func(*cognitoidentityprovider.Options)) (*cognitoidentityprovider.DeleteUserPoolClientOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteUserPoolClient", varargs...)
	ret0, _ := ret[0].(*cognitoidentityprovider.DeleteUserPoolClientOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteUserPoolClient indicates an expected call of DeleteUserPoolClient.
func (mr *MockCognitoClientMockRecorder) DeleteUserPoolClient(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserPoolClient", reflect.TypeOf((*MockCognitoClient)(nil).DeleteUserPoolClient), varargs...)
}

// DescribeResourceServer mocks base method.
func (m *MockCognitoClient) DescribeResourceServer(ctx context.Context, params *cognitoidentityprovider.DescribeResourceServerInput, optFns ...func(*cognitoidentityprovider.Options)) (*cognitoidentityprovider.DescribeResourceServerOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeResourceServer", varargs...)
	ret0, _ := ret[0].(*cognitoidentityprovider.DescribeResourceServerOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeResourceServer indicates an expected call of DescribeResourceServer.
func (mr *MockCognitoClientMockRecorder) DescribeResourceServer(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeResourceServer", reflect.TypeOf((*MockCognitoClient)(nil).DescribeResourceServer), varargs...)
}

// UpdateResourceServer mocks base method.
func (m *MockCognitoClient) UpdateResourceServer(ctx context.Context, params *cognitoidentityprovider.UpdateResourceServerInput, optFns ...func(*cognitoidentityprovider.Options)) (*cognitoidentityprovider.UpdateResourceServerOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateResourceServer", varargs...)
	ret0, _ := ret[0].(*cognitoidentityprovider.UpdateResourceServerOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateResourceServer indicates an expected call of UpdateResourceServer.
func (mr *MockCognitoClientMockRecorder) UpdateResourceServer(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateResourceServer", reflect.TypeOf((*MockCognitoClient)(nil).UpdateResourceServer), varargs...)
}

// UpdateUserPoolClient mocks base method.
func (m *MockCognitoClient) UpdateUserPoolClient(ctx context.Context, params *cognitoidentityprovider.UpdateUserPoolClientInput, optFns ...func(*cognitoidentityprovider.Options)) (*cognitoidentityprovider.UpdateUserPoolClientOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateUserPoolClient", varargs...)
	ret0, _ := ret[0].(*cognitoidentityprovider.UpdateUserPoolClientOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserPoolClient indicates an expected call of UpdateUserPoolClient.
func (mr *MockCognitoClientMockRecorder) UpdateUserPoolClient(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserPoolClient", reflect.TypeOf((*MockCognitoClient)(nil).UpdateUserPoolClient), varargs...)
}
