name: Release

on:
  release:
    # types: [created]
    types: [published]

jobs:
  style-check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        if: github.event_name == 'pull_request'
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.46.2
          args: --timeout=3m
  go-unit-test:
    runs-on: ubuntu-20.04
    needs: [style-check]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Vendor
        run: make vendor
      - name: Test
        run: make test
  docker-build:
    runs-on: ubuntu-latest
    needs: go-unit-test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Gcloud Login
        uses: google-github-actions/setup-gcloud@a48b55b3b0eeaf77b6e1384aab737fbefe2085ac
        with:
          version: '386.0.0'
          project_id: gloo-mesh
          service_account_key: ${{ secrets.ARTIFACT_PUSHER_JSON_KEY }}
          export_default_credentials: true
      - name: Publish Docker image
        env:
          TAGGED_VERSION: ${{ github.event.release.tag_name }}
          PROJECT: gloo-mesh
        run: |
          make docker-release
  release-helm:
    name: Release gloo-portal-idp-connect helm chart
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Gcloud Login
        uses: google-github-actions/setup-gcloud@a48b55b3b0eeaf77b6e1384aab737fbefe2085ac
        with:
          version: '386.0.0'
          project_id: gloo-mesh
          service_account_key: ${{ secrets.GLOO_RELEASE_ADMIN }}
          export_default_credentials: true
      - name: Publish Helm
        env:
          TAGGED_VERSION: ${{ github.event.release.tag_name }}
        run: |
          make publish-chart
