name: Release

on:
  release:
    # types: [created]
    types: [published]

jobs:
  style-check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        if: github.event_name == 'pull_request'
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54.2
          args: --timeout=3m
  docker-release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Gcloud Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.ARTIFACT_PUSHER_JSON_KEY }}
          project_id: gloo-mesh
          create_credentials_file: true

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 416.0.0

      - name: Publish Docker image
        env:
          TAGGED_VERSION: ${{ github.event.release.tag_name }}
          PROJECT: gloo-mesh
        run: |
          make docker-release
  release-helm:
    name: Release gloo-portal-idp-connect helm chart
    runs-on: ubuntu-24.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout
        uses: actions/checkout@v3

      - name: Gcloud Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GLOO_RELEASE_ADMIN }}
          project_id: gloo-mesh
          create_credentials_file: true

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 416.0.0

      - name: Publish Helm
        env:
          TAGGED_VERSION: ${{ github.event.release.tag_name }}
        run: |
          make publish-chart
